class Instructions < StructuredDocument
  paragraph_type( :introduction,
                  font_name: :mono,
                  font_size: 14,
                  font_emphasis: :none )

  # we're going to left his code here as an example of which
  # type of code is going to be generated by paragraph_type
  def warning( text )
    paragraph = Paragraph.new( :arial, 22, :bold, text )
    self << paragraph
  end

  def step( text )
    paragraph = Paragraph.new( :nimbus, 14, :none, text )
    self << paragraph
  end
end
